= Give developers autonomy
:author: Philip Nelson

Most architects begin their career as developers.
An architect has new responsibilities and greater authority in determining how a system is built.
You may find it difficult to let go of what you did as a developer in your new role as an architect.
Worse, you may feel it's important for you to exercise a lot of control over how developers do their work to implement the design.
It will be very important to your success and your team's success to give all of your teammates enough autonomy to exercise their own creativity and abilities.

As a developer you rarely get the time to sit back and really look at how the whole system fits together.
As an architect, this is your main focus.
While developers are furiously building classes, methods, tests, user interfaces and databases, you should be making sure that all those pieces work well together.
Listen for points of pain and try to improve them.
Are people are having trouble writing tests?
Improve the interfaces and limit dependencies.
Do you understand where you actually need abstraction and where you don't?
Work for domain clarity.
Do you know what order to build things in?
Build your project plan.
Are developers consistently making common mistakes using an API you designed?
Make the design more obvious.
Do people really understand the design?
Communicate and make it clear.
Do you really understand where you need to scale and where you don't?
Work with your customer and learn their business model.

If you're doing a great job of being an architect, you really shouldn't have enough time to interfere with developers.
You do need to watch closely enough to see that the design is being implemented as intended.
You do not need to be standing over people's shoulders to accomplish that goal.
It's reasonable to make suggestions when you see people struggling, but it's even better if you create the environment where they come and ask you for suggestions.
If you are good, you will deftly walk the fine line between guaranteeing a successful architecture and limiting the creative and intellectual life of your developers and teammates.
