= ﻿The title of software architect has only lower-case 'a's; deal with it
:author: Barry Hawkins

A disappointing trend has been in bloom for some time now within software development; the attempt to professionalize the practice of software architecture as one on par with the classical school of Architecture.
This seems to stem from some need for further legitimization of one's accomplishment beyond acknowledgment among one's peers and employer.
By comparison, Architecture itself was not professionalized until the late 19th century, at least a few millennia after the practice had been around.
It would be no great stretch to say that some software architects seem a bit eager by comparison.

Software architecture is a craft, and it certainly takes practice and discipline to achieve success in the field.
That said, software development is still a relatively nascent endeavor.
We don't even know enough about this practice to adequately professionalize it.
Despite its youth, software development's product has become a highly valued tool, and as such, the accomplished individuals (as well as those who wish to be seen as accomplished) have enjoyed levels of compensation on par with the leading professional fields, including medicine, accounting, and law.

Practitioners of software development enjoy considerable compensation for work that is highly creative and exploratory.
The fruits of our labors have been used to accomplish many significant milestones, some that benefit all of mankind.
The barriers to entry are largely one's own merit and opportunity; the fully-professionalized fields undergo programs of study and internship that dwarf our own.
Dwell on that for a moment and ponder how much cause we have to be content, and just how brash it is to insist that software architect be considered a title that sits as peer to Lawyer, Doctor, and Architect.

The title of software architect has only lower-case 'a's; deal with it.
