= ﻿Heterogeneity Wins
:author: Edward Garson

The natural evolution of computer technology has brought about important changes with respect to the tools that architects can use to build software systems.
These changes have brought about a resurgence of interest in polyglot programming, which refers to the use of more than one core language in the provision of a software system.

Polyglot programming is not a new concept: one prominent example from the past is front-end Visual Basic clients supported by COM objects authored in C++ on the back-end.
Fundamentally speaking, this architecture leveraged what those languages were good at in their heyday.

So what changes took place to fuel this renewed interest in polyglot programming?

The change is that technical standards together with ever-increasing bandwidth and computing resources conspired to make text-based protocols viable: gone are the days of arcane binary protocols as a pre-requisite to efficient distributed systems.
Text-based remote interoperability largely began with XML/SOAP-based web services and continues to evolve with RESTful architectural styles and other supporting (but no less important) protocols such as Atom and XMPP.

This new breed of technologies creates far broader opportunities for heterogeneous development than ever before, simply because the payloadis formatted text, which is universally generated and consumed.
Heterogeneous development affords using the right tool for the job, and text-based interop has blown the doors off what was previously possible.

Architects can now combine specific, powerful tools that move the yardstick from previously being able to employ the right language to now being able to employ the right paradigm.
Programming languages support different paradigms, in that some are object-oriented, while others are functional or excel at concurrent programming.
Some of these paradigms are a perfect match for particular problems or domains, while others are a poor fit.
Today, however, it is possible to 'mash-up' some rather unconventional and seemingly dissonant tools into elegant solutions rather more easily than in the past.

The effects of this change has begun, and manifests itself as a combinatorial increase in the architectural topology of modern software systems.
This is not just a reflection of their inherent diversity, but a testament to new possibilities.

While choice is not always a good thing, it is 'less worse' than the alternative in the context of modern software architecture.
As an industry, we are faced with very serious problems[The impending multicore era may well prove to be the most significant problem yet faced by the software development community.] and we need all the interoperability we can get, particularly as the incumbent platforms are not well equipped to resolve them footnote:[The Free Lunch is Over - Herb Sutter, http://www.gotw.ca/publications/concurrency-ddj.htm].

Your job as architect has become even more challenging, because technology silos are crumbling in the face of new possibilities: embrace this, think outside the stack, and leverage the new diversity: heterogeneity wins.
