= ﻿Learn from Architects of Buildings
:author: Keith Braithwaite

[quote, Spiro Kostof]
"Architecture is a social act and the material theater of human activity."

How many software architects see their role as exclusively, or primarily technical?
Is it not rather that they are the conciliators, go–betweens and arbiters of the warring factions among the stake-holders?
How many approach their work in a purely intellectual spirit, without giving proper weight to the human factors of their job?

[quote,Frank Lloyd Wright]
"A great architect is not made by way of a brain nearly so much as he is made by way of a cultivated, enriched heart."

What more strongly marks out the architects in your organization: raw intellectual horsepower and vast capacity to recall technical minutia, or taste, refinement and generosity of spirit?
Under which tendency would you prefer to work?

[quote,ibid]
"A doctor can bury his mistakes but an architect can only advise his client to plant vines."

Is the "maintenance" of "legacy" systems anything more than pruning those vines?
Would you, as an architect, have the intestinal fortitude to scrap a piece of work that had failed?
Or would you cover it up?
Wright also said that the architect's best friend was the sledgehammer.
What have you demolished recently?

[quote,Karen Moyer]
"Architects believe that not only do they sit at the right hand of God, but that if God ever gets up, they take the chair"

For "God" read "customer".

[quote,Henry Watton]
"In architecture as in all other operative arts, the end must direct the operation.
The end is to build well.
Well building has three conditions: Commodity, Firmness and Delight.""

When was the last time you saw a piece of software who's architecture gave you any delight?
Do you aim to give delight with your work?

[quote,John Ruskin]
"No person who is not a great sculptor or painter can be an architect.
If he is not a sculptor or painter, he can only be a builder"

Does artistry play its proper part in your architecture?
Is the assemblage of components to make systems informed by a painterly concern for shape and texture, with a sculptural sense of balance and implied motion, of the importance of negative space?

And finally, no gloss is required on this comment, a sure remedy for the software architect's most damaging syndrome.

[quote,ibid]
"It seems a fantastic paradox, but it is nevertheless a most important truth, that no architecture can be truly noble which is not imperfect."
