= Welcome to the Real World
:author: Gregor Hohpe

Engineers like precision, especially software engineers who live in the realm of ones and zeros.
They are used to working with binary decisions, one or zero, true or false, yes or no.
Everything is clear and consistent, guaranteed by foreign key constraints, atomic transactions, and check sums.

Unfortunately, the real world is not quite that binary.
Customers place orders, just to cancel them a moment later.
Checks bounce, letters are lost, payments delayed, and promises broken.
Data entry errors are bound to happen every so often.
Users prefer "shallow" user interfaces, which give them access to many functions at once without being boxed into a lengthy, one-dimensional "process", which is easier to program and seems more "logical" to many developers.
Instead of the call stack controlling the program flow, the user is in charge.

Worse yet, widely distributed systems introduce a whole new set of inconsistencies into the game.
Services may not be reachable, change without prior notice, or do not provide transactional guarantees.
When you run applications on thousands of machine, failure is no longer a question of "if", but of "when".
These systems are loosely coupled, asynchronous, concurrent, and do not adhere to traditional transaction semantics.
You should have taken the blue pill!

As computer scientists' brave new world is crumbling, what are we to do?
As so often, awareness is a first important step towards a solution.
Say good bye to the good old predictive call-stack architecture, where you get to define what happens when and in what order.
Instead, be ready to respond to events at any time in any order, regaining your context as needed.
Make asynchronous requests concurrently instead of calling methods one by one.
Avoid complete chaos by modeling your application using event-driven process chains or state models.
Reconcile errors through compensation, retry, or tentative operations.

Sounds scary and more than you bargained for?
Luckily, the real world had to deal with the same issues for a long time: delayed letters, broken promises, messages crossing in transit, payments posted to the wrong account -- the examples are countless.
Accordingly, people had to resend letters, write off bad orders, or tell you to ignore the payment reminder in case you already sent a payment.
So don't just blame the real world for your headaches, but also use it as a place to look for solutions.
After all, Starbucks does not two-phase commit either footnote:[http://www.eaipatterns.com/ramblings/18_starbucks.html].
Welcome to the real world.
